- name: Ensure required directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/monitoring/.config/systemd/user/
    - /home/monitoring/prometheus

- name: Download and install Prometheus
  register: install_prometheus
  ansible.builtin.unarchive:
    dest: /home/monitoring/prometheus
    remote_src: true
    # TODO: Get architecture dynamically instead of hardcoding it
    src: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-arm64.tar.gz
    extra_opts:
      - --strip-components=1
      - --exclude=prometheus.yml

- name: Configure systemd unit
  register: configure_systemd_unit
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /home/monitoring/.config/systemd/user/prometheus.service

- name: Configure Prometheus instance
  register: configure_prometheus
  ansible.builtin.template:
    src: "{{ playbook_dir }}/prometheus.yml"
    dest: /home/monitoring/prometheus/prometheus.yml

- name: Restart Prometheus service
  when: install_prometheus.changed or configure_systemd_unit.changed
  ansible.builtin.systemd:
    name: prometheus
    scope: user
    state: restarted
    enabled: true
    daemon_reload: true

- name: Get Prometheus process ID
  register: get_prometheus_pid
  when: configure_prometheus.changed
  ansible.builtin.shell: systemctl --user show --property MainPID --value prometheus

- name: Reload Prometheus configuration
  when: configure_prometheus.changed
  ansible.builtin.shell: kill -1 {{ get_prometheus_pid.stdout }}
