- name: Install packages
  become: true
  ansible.builtin.apt:
    deb: "{{ item }}"
  with_items:
    # TODO: Investigate the order of dependencies here, previously `docker-ce` has needed `docker-ci-cli` first on a clean install
    - "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/containerd.io_{{ containerd_version }}_amd64.deb"
    - "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce-cli_{{ docker_version }}_amd64.deb"
    - "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-ce_{{ docker_version }}_amd64.deb"
    - "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-buildx-plugin_{{ docker_buildx_version }}_amd64.deb"
    - "https://download.docker.com/linux/ubuntu/dists/jammy/pool/stable/amd64/docker-compose-plugin_{{ docker_compose_version }}_amd64.deb"
