steps:
  - label: ":writing_hand: Back up Writefreely instance"
    key: backup
    command: .buildkite/backup-write/backup.sh
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/backup
    concurrency: 1
    artifact_paths:
      - deploy/boyd/writefreely/backups/**/*.tar

  - wait

  - label: ":aws: Upload backup to S3"
    command: .buildkite/backup-write/upload.sh
