steps:
  - label: ":writing_hand: Back up Writefreely instance"
    key: backup
    command: .buildkite/backup-writefreely/backup.sh
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/backup
    concurrency: 1
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
          mount-buildkite-agent: true

  - wait

  - label: ":aws: Upload backup to S3"
    command: .buildkite/backup-writefreely/upload.sh
