- name: Deploy Writefreely instance
  hosts: boyd
  gather_facts: false
  pre_tasks:
    - name: Create Write user
      become: true
      register: create_user
      ansible.builtin.user:
        name: write
        shell: /bin/bash
    - name: Enable linger for Write user
      become: true
      when: create_user.changed
      ansible.builtin.shell: loginctl enable-linger write
  roles:
    - role: ../../roles/writefreely
      remote_user: write
      vars:
        writefreely_version: "0.13.1"
    - role: ../../roles/nginx
      become: true
      vars:
        nginx_hostname: "write.nicholas.cloud"
