scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "node"
    scrape_interval: 15s
    static_configs:
      - targets: ["boyd:9100", "gandra-dee:9100", "gyro:9100"]
  - job_name: "nginx"
    static_configs:
      - targets: ["boyd:9110", "gandra-dee:9110", "gyro:9110"]
  - job_name: "buildkite"
    scrape_interval: 30s
    static_configs:
      - targets: ["boyd:9120"]
