- name: Ensure required directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/monitoring/.config/systemd/user/
    - /home/monitoring/grafana/

- name: Download and install Grafana
  register: install_grafana
  ansible.builtin.unarchive:
    dest: /home/monitoring/grafana/
    remote_src: true
    # TODO: Get architecture dynamically instead of hardcoding it
    src: https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-arm64.tar.gz
    extra_opts:
      - --strip-components=1

- name: Configure systemd unit
  register: configure_systemd_unit
  ansible.builtin.template:
    src: grafana.service.j2
    dest: /home/monitoring/.config/systemd/user/grafana.service

- name: Configure Grafana instance
  register: configure_grafana
  ansible.builtin.template:
    src: "{{ playbook_dir }}/grafana.ini"
    dest: /home/monitoring/grafana/conf/grafana.ini

- name: Restart Grafana service
  when: install_grafana.changed or configure_systemd_unit.changed or configure_grafana.changed
  ansible.builtin.systemd:
    name: grafana
    scope: user
    state: restarted
    enabled: true
    daemon_reload: true
