- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name:
      - nginx-extras
    state: latest

- name: Configure Nginx
  register: configure_nginx
  become: true
  ansible.builtin.copy:
    src: stub_status.nginx
    dest: /etc/nginx/sites-enabled/stub_status

# TODO: Add a rescue option to restore a backup of Nginx config/certs
- name: Validate Nginx configuration
  when: configure_nginx.changed
  become: true
  ansible.builtin.shell: nginx -t

- name: Restart Nginx
  when: configure_nginx.changed
  become: true
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: Ensure required directory exists
  ansible.builtin.file:
    path: /root/nginx-prometheus-exporter
    state: directory

- name: Download and install NGINX Exporter
  register: install_nginx_exporter
  ansible.builtin.unarchive:
    dest: /root/nginx-prometheus-exporter
    remote_src: true
    # TODO: Get architecture dynamically instead of passing a variable
    src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_prometheus_exporter_version }}/nginx-prometheus-exporter_{{ nginx_prometheus_exporter_version }}_linux_{{ goarch }}.tar.gz

- name: Configure systemd unit
  register: configure_systemd_unit
  ansible.builtin.copy:
    src: nginx-prometheus-exporter.service
    dest: /etc/systemd/system/nginx-prometheus-exporter.service

- name: Restart NGINX Exporter service
  when: install_nginx_exporter.changed or configure_systemd_unit.changed
  ansible.builtin.systemd:
    name: nginx-prometheus-exporter
    state: restarted
    enabled: true
    daemon_reload: true
