---
- name: Create a backup
  hosts: boyd
  remote_user: write
  gather_facts: false
  tasks:
    - name: Set backup date
      ansible.builtin.set_fact:
        backup_date: "{{ '%Y-%m-%dT%H:%M:%SZ' | strftime }}"
    - name: Ensure backup path exists
      ansible.builtin.file:
        path: /home/write/backups
        state: directory
        recurse: true
    - name: Stop Writefreely
      ansible.builtin.shell: systemctl --user stop writefreely
    - name: Create backup file of Writefreely data and credentials
      ansible.builtin.shell: tar --gzip --create --file /home/write/backups/{{ backup_date }}.tar --directory /home/write/writefreely keys writefreely.db
    - name: Restart Writefreely
      ansible.builtin.shell: systemctl --user start writefreely
    - name: Copy backup file to controller
      ansible.builtin.fetch:
        src: /home/write/backups/{{ backup_date }}.tar
        dest: backups
