- name: Deploy Writefreely (https://write.nicholas.cloud/)
  hosts: project_writefreely
  vars:
    writefreely_version: 0.13.1

  pre_tasks:
    - name: Install general tools and libraries
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - git
          - jq
        state: latest

    - name: Install D-Bus systemd user integration
      register: install_dbus_user_session
      become: true
      ansible.builtin.apt:
        name: dbus-user-session
        state: latest

    - name: Reboot if D-Bus systemd user integration was installed
      when: install_dbus_user_session.changed
      become: true
      ansible.builtin.reboot: ~

    - name: Keep system packages up to date
      become: true
      ansible.builtin.apt:
        autoremove: true
        update_cache: true
        name: "*"
        state: latest

    - name: Create Write user
      become: true
      register: create_user
      ansible.builtin.user:
        name: write
        shell: /bin/bash

    - name: Enable linger for Write user
      become: true
      when: create_user.changed
      ansible.builtin.shell: loginctl enable-linger write

  roles:
    - role: ../roles/nginx
      become: true
      vars:
        nginx_hostname: "write.nicholas.cloud"

  tasks:
    - name: Ensure required directory exists
      remote_user: write
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /home/write/writefreely/
        - /home/write/.config/systemd/user/

    - name: Download and install Writefreely
      when: ansible_local.write.versions.writefreely_version|d != writefreely_version
      register: install_writefreely
      remote_user: write
      ansible.builtin.unarchive:
        dest: /home/write/writefreely
        remote_src: true
        # TODO: Get architecture dynamically instead of hardcoding it
        src: https://github.com/writefreely/writefreely/releases/download/v{{ writefreely_version }}/writefreely_{{ writefreely_version }}_linux_arm64.tar.gz
        extra_opts:
          - "--strip-components=1"
          - "--preserve-permissions" # Permissions were causing changes on re-run

    - name: Configure Writefreely server
      register: configure_writefreely
      remote_user: write
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: config.ini
          dest: /home/write/writefreely/config.ini
        - src: writefreely.service.j2
          dest: /home/write/.config/systemd/user/writefreely.service

    - name: Restart Writefreely service
      when: install_writefreely.changed or configure_writefreely.changed
      remote_user: write
      ansible.builtin.systemd:
        name: writefreely
        scope: user
        state: restarted
        enabled: true
        daemon_reload: true
