services:
  ci:
    build:
      context: .
    userns: host
    network_mode: host
    working_dir: /hosting
    volumes:
      - ..:/hosting
    environment:
      - BUILDKITE_PIPELINE_SLUG
      - VAULT_ADDR
      - VAULT_TOKEN
