- name: Ensure required directory exists
  ansible.builtin.file:
    path: /root/node_exporter
    state: directory

- name: Download and install Node Exporter
  register: install_node_exporter
  ansible.builtin.unarchive:
    dest: /root/node_exporter
    remote_src: true
    # TODO: Get architecture dynamically instead of passing a variable
    src: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ goarch }}.tar.gz
    extra_opts:
      - --strip-components=1

- name: Configure systemd unit
  register: configure_systemd_unit
  ansible.builtin.copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: Restart Node service
  when: install_node_exporter.changed or configure_systemd_unit.changed
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
    enabled: true
    daemon_reload: true
