steps:
  - label: ":plausible: Back up Plausible instance"
    key: backup
    command: .buildkite/backup-plausible/backup.sh
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/backup
    concurrency: 1
    artifact_paths:
      - deploy/gandra-dee/plausible/backups/**/*.tar
    plugins:
      - docker-compose#v3.10.0:
          run: ci
          config: .buildkite/docker-compose.yml
          env:
            - BUILDKITE_PIPELINE_SLUG
            - TAILSCALE_API_TOKEN
            - VAULT_ADDR
            - VAULT_TOKEN

  - wait

  - label: ":aws: Upload backup to S3"
    command: .buildkite/backup-plausible/upload.sh
