receivers:
  prometheus/vault:
    config:
      scrape_configs:
        - job_name: vault
          scrape_interval: 60s
          metrics_path: /v1/sys/metrics
          authorization:
            credentials: "{{ vault_token }}"
          static_configs:
            - targets: [vault.nicholas.cloud]

  prometheus/node:
    config:
      scrape_configs:
        - job_name: blog
          scrape_interval: 15s
          static_configs:
            - targets:
                - blog:9100
        - job_name: home
          scrape_interval: 60s
          static_configs:
            - targets:
                - boyd:9100
                - gyro:9100

processors:
  batch:

exporters:
  otlp/vault:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "{{ honeycomb_ingest_api_key }}"
      "x-honeycomb-dataset": "vault"
  otlp/node:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "{{ honeycomb_ingest_api_key }}"
      "x-honeycomb-dataset": "node"

service:
  pipelines:
    metrics/vault:
      receivers: [prometheus/vault]
      processors: [batch]
      exporters: [otlp/vault]
    metrics/node:
      receivers: [prometheus/node]
      processors: [batch]
      exporters: [otlp/node]
