receivers:
  prometheus/vault:
    config:
      scrape_configs:
        - job_name: vault
          scrape_interval: 60s
          metrics_path: /v1/sys/metrics
          authorization:
            credentials: "{{ vault_token }}"
          static_configs:
            - targets: [vault.nicholas.cloud]

processors:
  batch:

exporters:
  otlp/vault:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "{{ honeycomb_ingest_api_key }}"
      "x-honeycomb-dataset": "vault"

service:
  pipelines:
    metrics/vault:
      receivers: [prometheus/vault]
      processors: [batch]
      exporters: [otlp/vault]
