- name: Deploy Gyro
  hosts: gyro
  gather_facts: false
  pre_tasks:
    - name: Install general tools and libraries
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - git
          - jq
        state: latest
    - name: Install D-Bus systemd user integration
      register: install_dbus_user_session
      become: true
      ansible.builtin.apt:
        name: dbus-user-session
        state: latest
    - name: Reboot if D-Bus systemd user integration was installed
      when: install_dbus_user_session.changed
      become: true
      ansible.builtin.reboot: ~
    - name: Keep system packages up to date
      become: true
      ansible.builtin.apt:
        autoremove: true
        update_cache: true
        name: "*"
        state: latest
  roles:
    - role: ../../roles/node-exporter
      become: true
      vars:
        node_exporter_version: "1.6.1"
        goarch: arm64

- ansible.builtin.import_playbook: "{{ playbook_dir }}/vault/main.yml"

- ansible.builtin.import_playbook: "{{ playbook_dir }}/monitoring/main.yml"
