- name: Ensure required directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/plausible/plausible-hosting
    - /home/plausible/.config/systemd/user/

- name: Configure Plausible
  register: configure_plausible
  vars:
    # TODO: Move these credentials over to Vault
    plausible_admin_password: "{{ lookup('community.general.passwordstore', 'website/plausible-admin-password') }}"
    plausible_secret_key: "{{ lookup('community.general.passwordstore', 'website/plausible-secret-key') }}"
    mailgun_relay_password: "{{ lookup('community.general.passwordstore', 'website/mailgun-relay-password') }}"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: plausible-conf.env.j2
      dest: /home/plausible/plausible-hosting/plausible-conf.env
      mode: "0600"
    - src: docker-compose.yml.j2
      dest: /home/plausible/plausible-hosting/docker-compose.yml
      mode: "0644"
    - src: clickhouse-config.xml
      dest: /home/plausible/plausible-hosting/
      mode: "0644"
    - src: clickhouse-user-config.xml
      dest: /home/plausible/plausible-hosting/
      mode: "0644"
    - src: plausible.service.j2
      dest: /home/plausible/.config/systemd/user/plausible.service
      mode: "0644"

- name: Ensure Docker images are up to date
  when: configure_plausible.changed
  ansible.builtin.shell: docker compose pull
  args:
    chdir: /home/plausible/plausible-hosting

- name: Restart Plausible
  when: configure_plausible.changed
  ansible.builtin.systemd:
    name: plausible
    scope: user
    state: restarted
    enabled: true
    daemon_reload: true
