steps:
  - label: ":vault: Back up Vault instance"
    command: .buildkite/backup-vault/backup.sh
    concurrency_group: $BUILDKITE_PIPELINE_SLUG/backup
    concurrency: 1
    artifact_paths:
      - vault-*.snap

  - wait

  - label: ":aws: Upload backup to S3"
    command: .buildkite/backup-vault/upload.sh
