- name: Ensure required directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/vault/.config/systemd/user/
    - /home/vault/data

- name: Download and install Vault
  when: ansible_local.vault.versions.vault_version|d != vault_version
  register: install_vault
  ansible.builtin.unarchive:
    dest: /home/vault/
    remote_src: true
    # TODO: Get architecture dynamically instead of hardcoding it
    src: https://releases.hashicorp.com/vault/{{ vault_version }}/vault_{{vault_version}}_linux_arm64.zip

- name: Allow Vault to call mlock()
  when: install_vault.changed
  become: true
  remote_user: nchlswhttkr
  # https://support.hashicorp.com/hc/en-us/articles/115012787688-Vault-and-mlock-
  ansible.builtin.shell: setcap cap_ipc_lock=+ep $(readlink -f /home/vault/vault)

- name: Configure Vault server
  register: configure_vault
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "{{ playbook_dir }}/config.hcl"
      dest: /home/vault/config.hcl
    - src: vault.service.j2
      dest: /home/vault/.config/systemd/user/vault.service

- name: Restart Vault service
  when: install_vault.changed or configure_vault.changed
  ansible.builtin.systemd:
    name: vault
    scope: user
    state: restarted
    enabled: true
    daemon_reload: true

- name: Pause for Vault to be unsealed
  when: install_vault.changed or configure_vault.changed
  ansible.builtin.pause:
