- name: Deploy Plausible instance
  hosts: gandra-dee
  gather_facts: false
  pre_tasks:
    - name: Create local user
      become: true
      register: create_user
      ansible.builtin.user:
        name: plausible
        shell: /bin/bash
        append: true
        groups: [docker]
    - name: Enable linger for local user
      become: true
      when: create_user.changed
      ansible.builtin.shell: loginctl enable-linger plausible
  roles:
    - role: ../../roles/plausible
      remote_user: plausible
      vars:
        # TODO: Extract other version variables (databases) to this playbook
        plausible_version: "1.5.1"
    - role: ../../roles/nginx
      become: true
      vars:
        nginx_hostname: "plausible.nicholas.cloud"
