- name: Ensure required directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /home/write/writefreely/
    - /home/write/.config/systemd/user/

- name: Download and install Writefreely
  when: ansible_local.write.versions.writefreely_version|d != writefreely_version
  register: install_writefreely
  ansible.builtin.unarchive:
    dest: /home/write/writefreely
    remote_src: true
    # TODO: Get architecture dynamically instead of hardcoding it
    src: https://github.com/writefreely/writefreely/releases/download/v{{ writefreely_version }}/writefreely_{{ writefreely_version }}_linux_arm64.tar.gz
    extra_opts:
      - "--strip-components=1"
      - "--preserve-permissions" # Permissions were causing changes on re-run

- name: Configure Writefreely server
  register: configure_writefreely
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "{{ playbook_dir }}/config.ini"
      dest: /home/write/writefreely/config.ini
    - src: writefreely.service.j2
      dest: /home/write/.config/systemd/user/write.service

- name: Restart Writefreely service
  when: install_writefreely.changed or configure_writefreely.changed
  ansible.builtin.systemd:
    name: write
    scope: user
    state: restarted
    enabled: true
    daemon_reload: true
